server:
  port: 8084
spring:
  application:
    name: user-service
  config:
    import: optional:classpath:application-local.yaml
  cloud:
    nacos:
      server-addr: localhost:8848
  redis:
    host: localhost
    port: 16379
    timeout: 3000ms
app:
  db:
    host: 127.0.0.1
    port: 13306
    username: root
    password: your-mysql-password
    database: wmall-user
  jwt:
    location: classpath:wmall.jks
    alias: wmall
    password: your-jks-password
    tokenTTL: 30m
weixin:
  config:
    originalid: your-weixin-original-id
    token: your-weixin-token
    app-id: your-weixin-app-id
    app-secret: your-weixin-app-secret
